one_hot:
  tag_column: "tags"                # Column name with tags to encode
  output_column_prefix: one_hot_tags    # Prefix for output columns

tags_indices:
  NewEra: 1
  Classic: 2
  ContemporaryClassic: 3
  NonVegan: 4
  NonVegetarian: 5
  Strong: 6
  USA: 7
  Citrus: 8
  Brunch: 9
  Hangover: 10
  Mild: 11
  Expensive: 12
  StrongFlavor: 13
  Christmas: 14
  Beach: 15
  DinnerParty: 16
  Summer: 17
  Cold: 18
  Fruity: 19
  Breakfast: 20