one_hot:
  tag_column: "tags"                # Column name with tags to encode
  output_column_prefix: one_hot_tags    # Prefix for output columns

tags_indices:
  NewEra: 1
  Classic: 2
  ContemporaryClassic: 3
  NonVegan: 4
  NonVegetarian: 5
  IBA: 6
  Strong: 7
  Alcoholic: 8
  USA: 9
  Citrus: 10
  Brunch: 11
  Hangover: 12
  Mild: 13
  Expensive: 14
  StrongFlavor: 15
  Christmas: 16
  Beach: 17
  DinnerParty: 18
  Summer: 19
  Cold: 20
  Fruity: 21
  Breakfast: 22