tags_definitions:
  - tag: IBA
    ingredients: []
    threshold: 2
  - tag: NonVegan
    ingredients: []
    threshold: 1
    - tag: NonVegetarian
    ingredients: []
    threshold: 1
  - tag: Strong
    ingredients: []
    threshold: 2
  - tag: Classic
    ingredients: []
    threshold: 2
  - tag: ContemporaryClassic
    ingredients: []
    threshold: 2
  - tag: Alcoholic
    ingredients: []
    threshold: 1
  - tag: USA
    ingredients: []
    threshold: 2
  - tag: Asia
    ingredients: []
    threshold: 2
  - tag: Citrus
    ingredients: []
    threshold: 1
  - tag: Brunch
    ingredients: []
    threshold: 2
  - tag: Hangover
    ingredients: []
    threshold: 2
  - tag: Mild
    ingredients: []
    threshold: 2
  - tag: Expensive
    ingredients: []
    threshold: 2
  - tag: Savory
    ingredients: []
    threshold: 2
  - tag: StrongFlavor
    ingredients: []
    threshold: 2
  - tag: Sour
    ingredients: []
    threshold: 1
  - tag: Christmas
    ingredients: []
    threshold: 1
  - tag: Beach
    ingredients: []
    threshold: 2
  - tag: DinnerParty
    ingredients: []
    threshold: 2
  - tag: Summer
    ingredients: []
    threshold: 2
  - tag: Chilli
    ingredients: []
    threshold: 1
  - tag: Dairy
    ingredients: []
    threshold: 2
  - tag: Nutty
    ingredients: []
    threshold: 2
  - tag: Cold
    ingredients: []
    threshold: 2
  - tag: Fruity
    ingredients: []
    threshold: 2
  - tag: Breakfast
    ingredients: []
    threshold: 2
  - tag: NewEra
    ingredients: []
    threshold: 2