functions:
  assign_classic_tags: false
  assign_vegan_vegetarian_tags: true
  assign_other_tags: true

tags_definitions:
  classic_tags:
    - tag: NewEra
      ingredients: ['Soda water', 'Light Rum', 'Angostura Bitters', 'Coca-Cola', 
      'Sweet Vermouth', 'Campari', 'Powdered Sugar', 'Cherry', 'Dry Vermouth', 'Olive', 
      'Lime Juice', 'Salt', 'Triple Sec', 'Ice', 'Maraschino Cherry', 'Orange Peel', 
      'Ginger Ale', 'Lemon Juice', 'Amaretto', 'Sloe Gin', 'Southern Comfort', 'Lemon Peel', 
      'Orange Bitters', 'Yellow Chartreuse', 'Creme De Cacao', 'Light Cream', 'Nutmeg', 'Lemon vodka', 
      'Pineapple Juice', 'Blackberry Brandy', 'Kummel', 'Kahlua', 'White Creme de Menthe', 'Tea', 
      'Whipped Cream', 'Benedictine', 'Carbonated Water', 'Coffee Liqueur', 'Celery Salt', 'Tabasco Sauce', 
      'Tomato Juice', 'Worcestershire Sauce', 'Blue Curacao', 'Lemonade', 'Tia Maria', 'Maraschino Liqueur', 
      'Grenadine', 'Egg', 'Cachaca', 'Egg Yolk', 'Cognac', 'Cherry Brandy', 'Port', 'Chocolate Ice-cream', 'Dubonnet Rouge', 
      'Sugar Syrup', 'Pineapple', 'Tonic Water', 'Orange spiral', 'Strawberries', 'Heavy cream', 'Galliano', 'Irish Whiskey', 
      'Peach brandy', 'Sweet and Sour', 'Green Chartreuse', 'Drambuie', 'Orgeat Syrup', 'Grapefruit Juice', 
      'Raspberry syrup', 'Sherry', 'Coffee Brandy', 'Lime vodka', 'Lemon-lime soda']
    - tag: Classic 
      ingredients: [
      'Soda water', 'Light Rum', 'Lime', 'Mint', 'Sugar', 'Water', 'Angostura Bitters', 'Bourbon',
      'Lemon', 'Vodka', 'Gin', 'Tequila', 'Sweet Vermouth', 'Campari', 'Powdered Sugar',
      'Blended Whiskey', 'Cherry', 'Dry Vermouth', 'Olive', 'Lime Juice', 'Salt', 'Triple Sec',
      'Ice', 'Maraschino Cherry', 'Orange Peel', 'Ginger Ale', 'Apricot Brandy', 'Lemon Juice',
      'Sloe Gin', 'Southern Comfort', 'Lemon Peel', 'Orange Bitters', 'Yellow Chartreuse', 
      'Creme De Cacao', 'Brandy', 'Pineapple Juice', 'Blackberry Brandy', 'Dark Rum', 'Egg White', 
      'Club Soda', 'Apple Brandy', 'Applejack', 'Orange', 'Benedictine', 'Champagne', 'Grand Marnier', 
      'Bitters', 'Scotch', 'Coffee Liqueur', 'Celery Salt', 'Tomato Juice', 'Worcestershire Sauce', 
      'Blue Curacao', 'Orange Juice', 'Tia Maria', 'Grenadine', 'Egg', 'Cognac', 'Cherry Brandy', 
      'Port', 'Dubonnet Rouge', 'Sugar Syrup', 'Tonic Water', 'Red Wine', 'Sherry'
      ]
    - tag: ContemporaryClassic
      ingredients: []
  
  vegan_vegetarian_tags:
    - tag: NonVegan  
      ingredients: [
        'Light Rum', 'Bourbon', 'Vodka', 'Gin', 'Tequila', 'Sweet Vermouth', 'Campari', 
        'Powdered Sugar', 'Blended Whiskey', 'Brandy', 'Egg White', 'Kahlua', 'Lemon vodka', 
        'Egg', 'Egg Yolk', 'Chocolate Ice-cream', 'Galliano', 'Irish Whiskey', 'Peach brandy'
      ]
    - tag: NonVegetarian
      ingredients: [
        'Light Rum', 'Bourbon', 'Vodka', 'Gin', 'Tequila', 'Cream', 'Egg White', 'Kahlua', 
        'Egg', 'Egg Yolk', 'Chocolate Ice-cream', 'Galliano', 'Irish Whiskey', 'Peach brandy'
        ]
  other_tags:
    - tag: Strong
      ingredients: ['Vodka', 'Gin', 'Tequila', 'Blended Whiskey', 'Apricot Brandy', 
      'Dark Rum', 'Apple Brandy', 'Applejack',  
      ]
    - tag: USA
      ingredients: ['Bourbon', 'Coca-Cola', 'Blended Whiskey', 'Southern Comfort', 'Applejack', 'Club Soda']
    - tag: Citrus
      ingredients: ['Lime', 'Lemon', 'Lime Juice', 'Lemon Juice', 'Orange Peel', 'Orange', 'Orange Juice', 'Grapefruit Juice']
    - tag: Brunch
      ingredients: [
      'Orange Juice', 'Champagne', 'Tomato Juice', 'Lemon Juice', 'Pineapple Juice', 'Tea', 
      'Lemonade', 'Grapefruit Juice', 'Strawberries', 'Coffee Liqueur', 'Heavy cream', 
      'Coca-Cola', 'Tonic Water', 'Lime Juice', 'Egg', 'Egg Yolk', 'Grenadine', 
      'Celery Salt', 'Tabasco Sauce', 'Worcestershire Sauce'
      ]
    - tag: Hangover
      ingredients: [
        'Tomato Juice', 'Celery Salt', 'Tabasco Sauce', 'Worcestershire Sauce', 
        'Lemon Juice', 'Salt', 'Egg', 'Egg Yolk', 'Orange Juice', 'Lime Juice', 
        'Club Soda', 'Soda water', 'Tea', 'Tonic Water', 'Ginger Ale'
      ]
    - tag: Mild
      ingredients: [
        'Light Cream', 'Heavy cream', 'Whipped Cream', 'Tea', 'Orange Juice', 
        'Pineapple Juice', 'Sweet and Sour', 'Grenadine', 'Powdered Sugar', 
        'Sugar Syrup', 'Lemonade', 'Strawberries'
      ]
    - tag: Expensive
      ingredients: [
        'Champagne', 'Cognac', 'Grand Marnier', 'Benedictine', 'Scotch', 
        'Irish Whiskey', 'Green Chartreuse', 'Yellow Chartreuse', 'Drambuie',
        'Port', 'Red Wine', 'Wine', 'Galliano'
      ]
    - tag: StrongFlavor
      ingredients: [
        'Angostura Bitters', 'Campari', 'Scotch', 'Green Chartreuse', 
        'Yellow Chartreuse', 'Kahlua', 'Coffee Liqueur', 'Drambuie', 
        'Tia Maria'
      ]
    - tag: Christmas
      ingredients: [
        'Nutmeg', 'Brandy', 'Amaretto', 'Cinnamon', 'Egg Yolk', 
        'Egg White', 'Heavy Cream', 'Whipped Cream', 'Apple Brandy'
     ]
    - tag: Beach
      ingredients: [
        'Coconut Cream', 'Pineapple Juice', 'Coconut', 'Rum', 'Cachaca',
        'Orange Juice', 'Lime Juice', 'Grenadine', 'Blue Curacao'
      ]
    - tag: DinnerParty
      ingredients: [
        'Champagne', 'Dry Vermouth', 'Campari', 
        'Sweet Vermouth', 'Scotch', 'Cognac', 'Port', 'Grand Marnier'
      ]
    - tag: Summer
      ingredients: [
        'Mint', 'Lemon', 'Lime', 'Soda water', 'Tonic Water', 
        'Orange Juice', 'Lemon Juice', 'Lime Juice', 'Strawberries', 
        'Grapefruit Juice', 'Pineapple Juice', 'Ice'
      ]
    - tag: Cold
      ingredients:  [
        'Ice', 'Soda water', 'Tonic Water', 'Champagne', 
        'Club Soda', 'Carbonated Water', 'Whipped Cream'
      ]
    - tag: Fruity
      ingredients: [
        'Orange Juice', 'Pineapple Juice', 'Lemon Juice', 'Lime Juice', 
        'Grapefruit Juice', 'Strawberries', 'Banana', 'Cherry',
        'Lime', 'Orange', 'Peach brandy'
      ]
    - tag: Breakfast
      ingredients: [
        'Orange Juice', 'Champagne', 'Tomato Juice', 'Coffee Liqueur', 
        'Tea', 'Egg', 'Egg Yolk', 'Pineapple Juice', 'Lemon Juice'
      ]
