# configs/analysis_configs/general_analysis_config.yaml

functions:
  load_data: true                       # Set to true to load data in the general analysis
  generate_descriptive_stats: true      # Set to true to analyze data shema in the general analysis
  analyze_columns: true                 # Set to true to analyze columns
